### ISSUE TITLE
Bug: I tried to run this package but it wasn't working and i got this error 

### ISSUE THREAD

**Issue by Yashsharma4way** [kinde-oss/kinde-react-native-sdk-0-7x#17]
### Prerequisites

- [ ] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [ ] I have checked the latest version of the library to replicate my issue
- [ ] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/489e2ca9c3307c2b2e098a885e22f2239116394a/CONTRIBUTING.md)
- [ ] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/489e2ca9c3307c2b2e098a885e22f2239116394a/CODE_OF_CONDUCT.md)

### Describe the issue

I tried to run this package but it wasn't working and i got this error please check it.
![image](https://github.com/kinde-oss/kinde-react-native-sdk-0-7x/assets/105732254/e95422db-d060-439d-9207-537ca4db4900)

### Library URL

*

### Library version

*

### Operating system(s)

Windows

### Operating system version(s)

*

### Further environment details

*

### Additional information

*

**Comment by oliwolff1** [comment]
Hi @Yashsharma4way,
There are details on how to solve this issue in the current React Native SDK doc (under `General tips > Building Issues`): https://kinde.com/docs/developer-tools/react-native-sdk/#building-issues

I have attached an image with specific details that may help you solve your issue.
![image (78)](https://github.com/kinde-oss/kinde-react-native-sdk-0-7x/assets/28074898/7a459fa6-b677-496f-bf2d-548454b74d1d)

I will leave this issue open in case you come across further issues.

**Comment by oliwolff1** [comment]
I believe this issue has been solved.
