### ISSUE TITLE
Bug: kinde login in android (React Native)

### ISSUE THREAD

**Issue by Yashsharma4way** [kinde-oss/kinde-react-native-sdk-0-7x#28]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

InAppBrowser closes when I switch my app to go to gmail to check for OTP and when I come back to my application to enter the OTP, what I find is the InAppBrowser is closed so i need to start it again

Basically InAppBrowser is closed when we switch betweeen apps

facing this issue in android devices
```

export default function useAuth() {
  const dispatch = useDispatch();
  const client = new KindeSDK(
    config.VITE_KINDE_DOMAIN,
    config.VITE_KINDE_POST_CALLBACK_URL,
    config.VITE_KINDE_CLIENT_ID,
    config.VITE_KINDE_POST_LOGOUT_REDIRECT_URL,
  );
  const isAuthenticated = async () => await client.isAuthenticated;
  const getToken = async () => await Storage.getToken();
  const getProfile = async () => await client.getUserDetails();
  const getPermissions = async () => await client.getPermissions();
  const login = async () => {
    const token = await client.login();
    if (token) {
      jsonApiService.setUserToken(token.access_token);
      dispatch(setKindeToken(token));

      const userProfile = await client.getUserDetails();
      dispatch(setKindeUser(userProfile));

      const permission = await client.getPermissions();
      dispatch(setPermission(permission?.permissions));
      return true;
    }
    return false;
  };
```

### Library URL

https://github.com/kinde-oss/kinde-react-native-sdk-0-7x

### Library version

v1.1

### Operating system(s)

Windows

### Operating system version(s)

11

### Further environment details

"react-native": "0.72.6",
facing the issue for Android devices

**Comment by onderay** [comment]
@Yashsharma4way the github repo has been updated, about to confirm the issue you are facing has been fixed?

**Comment by bmpickford** [comment]
Not sure if you found a resolution @Yashsharma4way but I'm seeing this issue on version 1.3.0, likely related to https://github.com/proyecto26/react-native-inappbrowser/issues/213
