### ISSUE TITLE
Feature request: release to support expo sdk 51

### ISSUE THREAD

**Issue by mdj-uk** [kinde-oss/kinde-react-native-sdk-0-7x#38]
### Prerequisites

- [X] I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

After upgrading app from expo sdk 50 to 51, calling the `login` method from android app results in this error:
```
The method or property WebBrowser.openBrowserAsync is not available on android, are you sure you've linked all the native dependencies properly?
```
The `@next` branch works fine, thanks to PR #33 which bumps expo-web-browser from 12.1.1 to 12.8.2.  

### What solution would you like to see?

Would be nice to have a release so we can just `npm install @kinde-oss/react-native-sdk-0-7x@latest`

**Comment by simonszalai** [comment]
+1
