### ISSUE TITLE
Bug: Error log when closing web browser

### ISSUE THREAD

**Issue by bmpickford** [kinde-oss/kinde-react-native-sdk-0-7x#45]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

Given the below code, if I proceed to open the web browser but then "exit" the flow mid way through I get this error in the console: `Something wrong when trying to authenticating. Reason:  cancel`. This isn't really an error and is polluting logs with false positives.

```ts
try {
    const token = await client.register();
} catch(err: unknown) {
    // nothing
}
```

### Desired behaviour
Easiest solution without a breaking change would be to warn if `response.type` is `cancel` here: https://github.com/kinde-oss/kinde-react-native-sdk-0-7x/blob/main/src/SDK/Utils.ts#L183

But ideally the error is returned and we are able to handle it accordingly though

```ts
const { token, error } = await client.register();

// OR

try {
    const token = await client.register();
} catch(err: unknown) {
    // handle error here
}
```

### Library URL

https://github.com/kinde-oss/kinde-react-native-sdk-0-7x

### Library version

1.3.0

### Operating system(s)

iOS

### Operating system version(s)

all

**Comment by oliwolff1** [comment]
Hey @bmpickford,
Thanks for raising this PR.
I will look into this with my team and get back to you.

**Comment by bmpickford** [comment]
No worries, happy to put up a PR if needed

**Comment by oliwolff1** [comment]
Hey @bmpickford,
It would be awesome if you could put a PR up as my team will be able to review that and get a fix in quicker (if the PR looks good).
